### ISSUE TITLE
Add support for providing a kscript version

### ISSUE THREAD

**Issue by plusmobileapps** [plusmobileapps/kscript-action#1]
It would be nice to add support for selecting a kscript version to be installed in the docker container. 

[Conversation on kscript pull request](https://github.com/holgerbrandl/kscript/pull/315#issuecomment-825853508)

**Comment by plusmobileapps** [comment]
**Update**  At least on the docker-ception approach (not for the shell installation approach),  I believe that the error was from the JDK version being used with Zulu, replacing with the default one that was being used in v1 `java 11.0.10.hs-adpt` [fixes that issue](https://github.com/plusmobileapps/kotlin-scripting/pull/4/checks?check_run_id=2435747052). However there seems to be some docker configuration I am missing which I will pickup again later since its getting late.

---

@holgerbrandl I attempted to add support for the kscript version installed in the docker container for the GitHub Action and in both approaches I seem to be getting an exception for a missing class in kscript and wondering if you had any insight? Below are the two approaches I could come up with. 

## Docker-ception Approach

Per your suggestion of using the `docker --build-arg`, I came to discover that GitHub Actions does not really support this functionality quite yet. However there was a [proposed workaround for using GitHub Docker Action `--build-arg`](https://github.community/t/feature-request-build-args-support-in-docker-container-actions/16846/7) by essentially having the docker container then generate another docker container.

[Diff](https://github.com/plusmobileapps/kscript-action/compare/version-support?expand=1)

[GitHub Action run](https://github.com/plusmobileapps/kotlin-scripting/pull/4/checks?check_run_id=2435475635)

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/docopt/DocoptExitException
562
	at kscript.app.KscriptKt.main(Kscript.kt:90)
563
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
564
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
565
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
566
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
567
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:64)
568
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:176)
569
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:186)
570
Caused by: java.lang.ClassNotFoundException: org.docopt.DocoptExitException
571
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
572
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
573
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
574
	... 8 more
```

## Install kscript from `entrypoint.sh`

The second approach avoids the use of a second docker container, and instead moves the installation of kscript in the `entrypoint.sh`. This also seems to get the same exception and unsure of the cause 🤔 

[Diff](https://github.com/plusmobileapps/kscript-action/compare/main...kscript-version?expand=1)

[GitHub Action run](https://github.com/plusmobileapps/kotlin-scripting/runs/2433576885?check_suite_focus=true)

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/docopt/DocoptExitException
29
	at kscript.app.KscriptKt.main(Kscript.kt:90)
30
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
31
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
32
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
33
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
34
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:64)
35
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:176)
36
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:186)
37
Caused by: java.lang.ClassNotFoundException: org.docopt.DocoptExitException
38
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
39
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
40
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

**Comment by holgerbrandl** [comment]
Are you sure that you are using the latest version of the script repo? It could be that due to the transition to maven-central, the build was temporarily flawed.

I double-checked and https://search.maven.org/artifact/com.offbytwo/docopt/0.6.0.20150202/jar seems fine and correctly set.

**Comment by plusmobileapps** [comment]
@holgerbrandl I think it might have been because I was testing with kscript 3.0.1 because using the latest 3.0.2 did get the 2nd approach installing from the shell to [work successfully](https://github.com/plusmobileapps/kotlin-scripting/runs/2450302253?check_suite_focus=true). I think I will go ahead with the second approach as it doesn't involve copying everything over into the second docker container. 

I was thinking of versioning all of the other dependencies installed in the docker container and was curious what your thoughts were on adding those as parameters to the users in the action or if the kscript version is the only thing that should be supported in this action? Or do you think it's necessary to version the java, kotlin, maven, and gradle dependencies at all?

**Comment by holgerbrandl** [comment]
Indeed exposing kotlin and java as optional parameters seems a good idea. Not sure about gradle and maven, I'd consider them as not that important
